# fly.toml app configuration file generated for ranecdottodobot on 2026-02-01T16:41:07Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "ranecdottodobot"

[env]
  NODE_ENV = "production"

[[vm]]
  memory = "256mb"
  cpu_kind = "shared"
  cpus = 1

